package defpackage;

import java.util.concurrent.Future;

/* JADX INFO: loaded from: classes4.dex */
public interface DefaultSurfaceProcessorExternalSyntheticLambda10<T> extends lambdarelease5androidxcameracoreprocessingDefaultSurfaceProcessor, Future<T> {
    DefaultSurfaceProcessorExternalSyntheticLambda10<T> TuitionPaymentFragmentbindingInflater1(onFrameAvailable onframeavailable);

    DefaultSurfaceProcessorExternalSyntheticLambda10<T> TuitionPaymentFragmentspecialinlinedviewModeldefault1(DefaultSurfaceProcessorExternalSyntheticLambda9<T> defaultSurfaceProcessorExternalSyntheticLambda9);

    void TuitionPaymentFragmentspecialinlinedviewModeldefault1(DefaultSurfaceProcessorExternalSyntheticLambda14<T> defaultSurfaceProcessorExternalSyntheticLambda14);

    <R> DefaultSurfaceProcessorExternalSyntheticLambda10<R> TuitionPaymentFragmentspecialinlinedviewModeldefault2(DefaultSurfaceProcessorPendingSnapshot<R, T> defaultSurfaceProcessorPendingSnapshot);

    <R> DefaultSurfaceProcessorExternalSyntheticLambda10<R> TuitionPaymentFragmentspecialinlinedviewModeldefault2(lambdasafeProcess0androidxcameracoreprocessingInternalImageProcessor<R, T> lambdasafeprocess0androidxcameracoreprocessinginternalimageprocessor);
}
